name: dotnet format

on:
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
        command: 'validate *.sarif'
